import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/src/components/contexts/language_context";
import { ThemeProvider } from "@/src/components/contexts/theme_context";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Adrien Aga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
         <ThemeProvider>
          <LanguageProvider>
            <Toaster position="top-right" reverseOrder={false} />
            {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
