import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import { Roboto_Slab } from 'next/font/google';
import "./globals.css";
import { LanguageProvider } from "@/src/components/contexts/language_context";
import { ThemeProvider } from "@/src/components/contexts/theme_context";
import { Toaster } from "react-hot-toast";





const robotoSlab = Roboto_Slab({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto-slab', 
});

export const metadata: Metadata = {
  title: "Adrien Aga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoSlab.variable}`}>
      <body
        className="font-serif font-normal antialiased bg-black text-white"
      >
         <ThemeProvider>
          <LanguageProvider>
            <Toaster position="top-right" reverseOrder={false} />
            {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
