import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/src/components/contexts/language_context";
import { ThemeProvider } from "@/src/components/contexts/theme_context";
import { Toaster } from "react-hot-toast";


const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-oswald",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Adrien Aga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oswald.variable} ${inter.variable}`}>
      <body
        className="font-sans antialiased bg-black text-white"
      >
         <ThemeProvider>
          <LanguageProvider>
            <Toaster position="top-right" reverseOrder={false} />
            {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
